name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - "main"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  download-dobunezumi:
    runs-on: ubuntu-latest
    outputs:
      dobunezumi_path: ${{ steps.set-path.outputs.dobunezumi_path }}
      dobunezumi_version: ${{ steps.get-version.outputs.dobunezumi_version }}

    steps:
      - name: Get latest dobunezumi version
        id: get-version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/izquiratops/dobunezumi/releases/latest | jq -r '.tag_name')
          echo "dobunezumi_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Cache dobunezumi
        id: cache-dobunezumi
        uses: actions/cache@v3
        with:
          path: ~/.dobunezumi
          key: dobunezumi-${{ steps.get-version.outputs.version }}

      - name: Download dobunezumi if not cached
        if: steps.cache-dobunezumi.outputs.cache-hit != 'true'
        run: |
          DOWNLOAD_URL=$(curl -s https://api.github.com/repos/izquiratops/dobunezumi/releases/latest | jq -r '.assets[] | select(.name | contains("linux-amd64")) | .browser_download_url')
          curl -L $DOWNLOAD_URL -o ~/.dobunezumi.gz
          gunzip -c ~/.dobunezumi.gz
          chmod +x ~/.dobunezumi/dobunezumi

      - name: Set dobunezumi path
        id: set-path
        run: echo "dobunezumi_path=$HOME/.dobunezumi" >> $GITHUB_OUTPUT

  build-and-deploy:
    needs: download-dobunezumi
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore dobunezumi from cache
        uses: actions/cache@v3
        with:
          path: ~/.dobunezumi
          key: dobunezumi-${{ needs.download-dobunezumi.outputs.dobunezumi_version }}

      - name: Add dobunezumi to GITHUB_PATH
        run: echo "${{ needs.download-dobunezumi.outputs.dobunezumi_path }}" >> $GITHUB_PATH

      - name: Install JS dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4